[package]
name = "schnorr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k256 = "0.11.6"
rand_core = { version = "0.6.4", features = ["getrandom"] }
hex-literal = "0.3.4"